/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:752d666c-78ef-4b5e-8290-b82e61dc4c90",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Uxq9QssVY",
    "aws_user_pools_web_client_id": "31640e1vb0ef83km4njto50ptm",
    "oauth": {
        "domain": "mychalkboardc3782b84-c3782b84-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "cboardCourses-dev",
            "region": "eu-central-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "mycboardAPI",
            "endpoint": "https://66fxq4fl8b.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ],
    "aws_cloud_logic": "enable"
};


export default awsmobile;
